---
- name: Client Inital setup
  hosts: "{{host}}"
  tasks:
  - name: Create ansibleuser
    ansible.builtin.user:
      name: ansibleuser
      shell: /bin/bash
      password: "{{user_pass | password_hash('sha512')}}"
      home: /home/ansibleuser
      uid: 5005

  - name: Add ansibleuser to sudo users
    ansible.builtin.copy:
      dest: "/etc/sudoers.d/ansibleuser"
      content: "ansibleuser ALL=(ALL) NOPASSWD: ALL"

  - name: copy SSH Key to remote machine
    ansible.builtin.authorized_key:
     user: ansibleuser
     key: "{{lookup('file', '/home/ansibleuser/.ssh/id_rsa.pub')}}"
     state: present

  - name: sshd diasble password authentiacaion
    ansible.builtin.lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^PasswordAuthentication'
      line: 'PasswordAuthentication no'
      state: present
      backup: yes
    notify: restart ssh

  handlers:
  - name: restart ssh
    service:
      name: sshd
      state: restarted
