---
- name: ServiceNow Connection test with servicenow.itsm
  hosts: servicenow
  tasks:
  - name: Create test incident
    servicenow.itsm.incident:
      instance:
        host: "{{ SN_HOST }}"
        username: "{{ SN_USERNAME }}"
        password: "{{ SN_PASSWORD }}"
      caller: admin
      state: new
      short_description: Test incident
      impact: low
      urgency: low
      attachments:
        - path: sample_file.txt
      other:
        work_notes: |
          Sample work note from ansible
    register: result
