---
- name: ServiceNow Connection test
  hosts: localhost
  tasks:
  - name: Create an incident
    snow_record:
      username: pollaaji
      password: "vH$c-qi301Z2;R5:7Ur*d,:=@4,rQe;::_oLirUM,;0w)jLbDT?d<rc4=S+KGTyYfI?,pE}-kpi:[ep@m_;tEu]Kf{zf+K>b3T)a"
      instance: dev202515
      state: present
      data:
        short_description: "This is a test incident opened by Ansible"
        severity: 3
        priority: 2
    register: new_incident   
